//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "test_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub manager_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::test_manager::Entity",
        from = "Column::ManagerId",
        to = "super::test_manager::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TestManager,
}

impl Related<super::test_manager::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TestManager.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
